export const productData = [
    {
        name: 'Radio',
        description: 'A transistor radio from the dark ages',
        price: 21.99,
        image: '',
        category: 'Electronics',
        created_at: '21-20-2023 320:2929',
        updated_at: '',
        is_active: true,
        reviews: 20,
        avg: 3.6
    },
    {
        name: 'Nintendo DS',
        description: 'A gaming system built by Nintendo',
        price: 121.99,
        image: '',
        category: 'Electronics',
        created_at: '21-20-2023 320:2929',
        updated_at: '',
        is_active: true,
        reviews: 20,
        avg: 3.6
    },
    {
        name: 'Flash Drive 32GB',
        description: 'USB3 with 32GB of space',
        price: 11.99,
        image: '',
        category: 'Electronics',
        created_at: '21-20-2023 320:2929',
        updated_at: '',
        is_active: true,
        reviews: 20,
        avg: 3.6
    },
    {
        name: 'Led Zepplin II',
        description: 'A great album',
        price: 21.99,
        image: '',
        category: 'Media',
        created_at: '21-20-2023 320:2929',
        updated_at: '',
        is_active: true,
        reviews: 20,
        avg: 3.6
    },
    {
        name: 'Game of Thrones Full Collection',
        description: 'Winter is Coming',
        price: 121.99,
        image: '',
        category: 'Media',
        created_at: '21-20-2023 320:2929',
        updated_at: '',
        is_active: true,
        reviews: 20,
        avg: 3.6
    },
    {
        name: 'Supernatural Full Collection',
        description: 'Two brothers fight evil.',
        price: 101.99,
        image: '',
        category: 'Media',
        created_at: '21-20-2023 320:2929',
        updated_at: '',
        is_active: true,
        reviews: 20,
        avg: 3.6
    },
    {
        name: 'Call of Duty',
        description: 'Black Ops III',
        price: 21.99,
        image: '',
        category: 'Games',
        created_at: '21-20-2023 320:2929',
        updated_at: '',
        is_active: true,
        reviews: 20,
        avg: 3.6
    },
    {
        name: 'Skyrim',
        description: 'Bethesda creates',
        price: 31.99,
        image: '',
        category: 'Games',
        created_at: '21-20-2023 320:2929',
        updated_at: '',
        is_active: true,
        reviews: 20,
        avg: 3.6
    },
    {
        name: 'Overwatch',
        description: 'New game?',
        price: 31.99,
        image: '',
        category: 'Games',
        created_at: '21-20-2023 320:2929',
        updated_at: '',
        is_active: true,
        reviews: 20,
        avg: 3.6
    },
]