# Generated by Django 4.1.7 on 2023-02-24 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_paymentmethod'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paymentmethod',
            name='expiration_date',
        ),
        migrations.AddField(
            model_name='paymentmethod',
            name='expiration_mon',
            field=models.CharField(default='', max_length=160, null=True),
        ),
        migrations.AlterField(
            model_name='paymentmethod',
            name='card_number',
            field=models.CharField(default='', max_length=160, null=True),
        ),
        migrations.AlterField(
            model_name='paymentmethod',
            name='cardholder_name',
            field=models.CharField(default='', max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='paymentmethod',
            name='cvv',
            field=models.CharField(default='', max_length=100, null=True),
        ),
    ]
