# Generated by Django 4.1.7 on 2023-02-24 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_remove_paymentmethod_expiration_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentmethod',
            name='expiration_year',
            field=models.CharField(default='', max_length=160, null=True),
        ),
    ]
