# Generated by Django 4.1.7 on 2023-02-25 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_paymentmethod_card_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentmethod',
            name='cardholder_name',
            field=models.TextField(default=''),
        ),
    ]
