// Auth Dispatch States
export const SIGNUP_SUCCESS = 'SIGNUP_SUCCESS'
export const SIGNUP_FAIL = 'SIGNUP_FAIL'
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS'
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS'
export const LOGOUT_FAIL = 'LOGOUT_FAIL'
export const LOGIN_FAIL = 'LOGIN_FAIL'
export const LOAD_CURRENT_SUCCESS = 'LOAD_CURRENT_SUCCESS'
export const LOAD_CURRENT_FAIL = 'LOAD_CURRENT_FAIL'
export const LOAD_USERS_SUCCESS = 'LOAD_USERS_SUCCESS'
export const LOAD_USERS_FAIL = 'LOAD_USERS_FAIL'
export const UPDATE_USER_SUCCESS = 'UPDATE_USER_SUCCESS'
export const UPDATE_USER_FAIL = 'UPDATE_USER_FAIL'
export const REMOVE_USER_SUCCESS = 'REMOVE_USER_SUCCESS'
export const REMOVE_USER_FAIL = 'REMOVE_USER_FAIL'
export const LOAD_AUSER_SUCCESS = 'LOAD_AUSER_SUCCESS'
export const LOAD_AUSER_FAIL = 'LOAD_AUSER_FAIL'
export const LOAD_USERPROFILE_SUCCESS = 'LOAD_USERPROFILE_SUCCESS'
export const LOAD_USERPROFILE_FAIL = 'LOAD_USERPROFILE_FAIL'

// AUTH CART DISPATCH TYPES
export const ADD_TO_CART_SUCCESS = 'ADD_TO_CART_SUCCESS'
export const ADD_TO_CART_FAIL = 'ADD_TO_CART_FAIL'
export const LOAD_CART_SUCCESS = 'LOAD_CART_SUCCESS'
export const LOAD_CART_FAIL = 'LOAD_CART_FAIL'
export const REMOVE_ITEM_SUCCESS = 'REMOVE_ITEM_SUCCESS'
export const REMOVE_ITEM_FAIL = 'REMOVE_ITEM_FAIL'
export const TOTAL_CART_SUCCESS = 'TOTAL_CART_SUCCESS'
export const TOTAL_CART_FAIL = 'TOTAL_CART_FAIL'

// ALERT DISPATCH STATES
export const SET_ALERT = 'SET_ALERT'
export const REMOVE_ALERT = 'REMOVE_ALERT'

// Product Dispatch States
export const LOAD_BROWSELIST_SUCCESS = 'LOAD_BROWSELIST_SUCCESS'
export const LOAD_BROWSELIST_FAIL = 'LOAD_BROWSELIST_FAIL'
export const LOAD_PRODUCT_SUCCESS = 'LOAD_PRODUCT_SUCCESS'
export const LOAD_PRODUCT_FAIL = 'LOAD_PRODUCT_FAIL'
export const LOAD_NEXT_SUCCESS = 'LOAD_NEXT_SUCCESS'
export const LOAD_NEXT_FAIL = 'LOAD_NEXT_FAIL'
export const LOAD_PREV_SUCCESS = 'LOAD_PREV_SUCCESS'
export const LOAD_PREV_FAIL = 'LOAD_PREV_FAIL'

// Review Dispatch States
export const UPLOAD_REVIEW_SUCCESS = 'UPLOAD_REVIEW_SUCCESS'
export const UPLOAD_REVIEW_FAIL = 'UPLOAD_REVIEW_FAIL'
export const DESTROY_REVIEW_SUCCESS = 'DESTROY_REVIEW_SUCCESS'
export const DESTROY_REVIEW_FAIL = 'DESTROY_REVIEW_FAIL'

// PaymentMethod Dispatch States
export const LOAD_PM_SUCCESS = 'LOAD_PM_SUCCESS'
export const LOAD_PM_FAIL = 'LOAD_PM_FAIL'
export const LOAD_PMS_SUCCESS = 'LOAD_PMS_SUCCESS'
export const LOAD_PMS_FAIL = 'LOAD_PMS_FAIL'
export const UPLOAD_PM_SUCCESS = 'UPLOAD_PM_SUCCESS'
export const UPLOAD_PM_FAIL = 'UPLOAD_PM_FAIL'
export const DESTROY_PM_SUCCESS = 'DESTROY_PM_SUCCESS'
export const DESTROY_PM_FAIL = 'DESTROY_PM_FAIL'
