# Generated by Django 4.1.5 on 2023-02-20 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0003_alter_purchase_products_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('Electronics', 'Electronics'), ('Media', 'Media'), ('Games', 'Games')], default='Electronics', max_length=50),
        ),
        migrations.AddField(
            model_name='product',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='product_pics/'),
        ),
    ]
