# Generated by Django 4.1.2 on 2022-10-19 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchases', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='hased_cv',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='purchase',
            name='hashed_card',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='purchase',
            name='hashed_exp',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='purchase',
            name='usr_addr',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='purchase',
            name='usr_city',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='purchase',
            name='usr_email',
            field=models.CharField(default='', max_length=50),
        ),
    ]
