// Auth Dispatch States
export const SIGNUP_SUCCESS = 'SIGNUP_SUCCESS'
export const SIGNUP_FAIL = 'SIGNUP_FAIL'
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS'
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS'
export const LOGOUT_FAIL = 'LOGOUT_FAIL'
export const LOGIN_FAIL = 'LOGIN_FAIL'
export const LOAD_CURRENT_SUCCESS = 'LOAD_CURRENT_SUCCESS'
export const LOAD_CURRENT_FAIL = 'LOAD_CURRENT_FAIL'
export const LOAD_USERS_SUCCESS = 'LOAD_USERS_SUCCESS'
export const LOAD_USERS_FAIL = 'LOAD_USERS_FAIL'
export const UPDATE_USER_SUCCESS = 'UPDATE_USER_SUCCESS'
export const UPDATE_USER_FAIL = 'UPDATE_USER_FAIL'
export const REMOVE_USER_SUCCESS = 'REMOVE_USER_SUCCESS'
export const REMOVE_USER_FAIL = 'REMOVE_USER_FAIL'
export const LOAD_AUSER_SUCCESS = 'LOAD_AUSER_SUCCESS'
export const LOAD_AUSER_FAIL = 'LOAD_AUSER_FAIL'
export const LOAD_USERPROFILE_SUCCESS = 'LOAD_USERPROFILE_SUCCESS'
export const LOAD_USERPROFILE_FAIL = 'LOAD_USERPROFILE_FAIL'

// ALERT DISPATCH STATES
export const SET_ALERT = 'SET_ALERT'
export const REMOVE_ALERT = 'REMOVE_ALERT'
// Product Dispatch States
export const LOAD_PRODUCT_SUCCESS = 'LOAD_PRODUCT_SUCCESS'
export const LOAD_PRODUCT_FAIL = 'LOAD_PRODUCT_FAIL'
export const LOAD_PRODUCTS_SUCCESS = 'LOAD_PRODUCTS_SUCCESS'
export const LOAD_PRODUCTS_FAIL = 'LOAD_PRODUCTS_FAIL'
// REMOVE_PRODUCT_SUCCESS, REMOVE_PRODUCT_FAIL,
// UPLOAD_PRODUCT_SUCCESS, UPLOAD_PRODUCT_FAIL
